//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_Reg_form.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Login_Reg_form.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _40957fb4_00bb_4369_9df1_ef9e8f9b6c18 {
            get {
                object obj = ResourceManager.GetObject("_40957fb4_00bb_4369_9df1_ef9e8f9b6c18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4bb25bcc_cad2_47f5_b039_7af0115507c7 {
            get {
                object obj = ResourceManager.GetObject("_4bb25bcc-cad2-47f5-b039-7af0115507c7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4e6fd309_9c09_4adf_9ad2_5adddbb722e3 {
            get {
                object obj = ResourceManager.GetObject("_4e6fd309_9c09_4adf_9ad2_5adddbb722e3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _99c07a16_d9eb_44f7_aad8_d752d72bde43 {
            get {
                object obj = ResourceManager.GetObject("_99c07a16_d9eb_44f7_aad8_d752d72bde43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _b14cb4f8_2f74_4c83_99dc_02bbc77e19ed {
            get {
                object obj = ResourceManager.GetObject("_b14cb4f8_2f74_4c83_99dc_02bbc77e19ed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _b14cb4f8_2f74_4c83_99dc_02bbc77e19ed1 {
            get {
                object obj = ResourceManager.GetObject("_b14cb4f8_2f74_4c83_99dc_02bbc77e19ed1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _d5a611dc_03d0_4ad8_9e1d_6503718ccebe {
            get {
                object obj = ResourceManager.GetObject("_d5a611dc_03d0_4ad8_9e1d_6503718ccebe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _d7d7b8bc_c9f8_4bff_ad92_c16b3dce968f {
            get {
                object obj = ResourceManager.GetObject("_d7d7b8bc_c9f8_4bff_ad92_c16b3dce968f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bkash_Customer_Care1 {
            get {
                object obj = ResourceManager.GetObject("Bkash_Customer_Care1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images1 {
            get {
                object obj = ResourceManager.GetObject("images1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images2 {
            get {
                object obj = ResourceManager.GetObject("images2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_businessman_customer_logo_customer_service_computer_software_business_cdr_company {
            get {
                object obj = ResourceManager.GetObject("png_clipart_businessman_customer_logo_customer_service_computer_software_business" +
                        "_cdr_company", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_businessman_customer_logo_customer_service_computer_software_business_cdr_company1 {
            get {
                object obj = ResourceManager.GetObject("png_clipart_businessman_customer_logo_customer_service_computer_software_business" +
                        "_cdr_company1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_businessman_customer_logo_customer_service_computer_software_business_cdr_company2 {
            get {
                object obj = ResourceManager.GetObject("png_clipart_businessman_customer_logo_customer_service_computer_software_business" +
                        "_cdr_company2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_icon_flat_design_vector_5813082 {
            get {
                object obj = ResourceManager.GetObject("search_icon_flat_design_vector_5813082", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_icon_flat_design_vector_58130821 {
            get {
                object obj = ResourceManager.GetObject("search_icon_flat_design_vector_58130821", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_icon_flat_design_vector_58130822 {
            get {
                object obj = ResourceManager.GetObject("search_icon_flat_design_vector_58130822", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_icon_flat_design_vector_58130823 {
            get {
                object obj = ResourceManager.GetObject("search_icon_flat_design_vector_58130823", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
